global:
  scrape_interval: 2s
  evaluation_interval: 2s

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ "alertmanager:9093" ]
rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'Prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: "DigitalMenu"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:10000" ]
        labels:
          application: "DigitalMenu"

  - job_name: "NodeExporter"
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: "Docker Containers"
    static_configs:
      - targets: [ "cadvisor:8080" ]