name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Docker-Compose
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "./docker-compose.yml"

      - name: Cache SonarCloud Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml', 'pom.xml') || github.sha }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Chown Data Folder
        run: sudo chown -R $USER:$USER ./data

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Build and Push
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          #        tags: kimleangk/hang-api:${{ github.run_number }}
          tags: kimleangk/hang-api:latest
          cache-from: type=registry,ref=kimleangk/hang-api:buildcache
          cache-to: type=registry,ref=kimleangk/hang-api:buildcache,mode=max

      - name: Install Trivy
        run: |
          sudo apt install -y trivy

      - name: Scan Dependencies
        run: trivy fs .

      - name: Scan docker image
        run: trivy image kimleangk/hang-api:latest