name: Scan

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Install Trivy
        run: |
          sudo apt install -y trivy

      - name: Scan Dependencies
        run: trivy fs .

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Docker-Compose
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "./docker-compose.yml"

      - name: Cache SonarCloud Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml', 'pom.xml') || github.sha }}
          restore-keys: ${{ runner.os }}-m2

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=KimleangSama_Hang-API

      - name: Run Tests Coverage
        run: mvn -B test verify --file pom.xml -Pcoverage

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Chown Data Folder
        run: sudo chown -R $USER:$USER ./data

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            ${{ github.workspace }}/target/site/jacoco/

      - name: JaCoCo Report
        id: jacoco-report
        uses: Madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 60
          title: '# :recycle: Coverage Report'
          update-comment: true
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.6
